apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: django-app
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        location /static/ {
            alias /data/static/;
        }
        location / {
            proxy_pass http://app-service:8000; # point to django application's host and port
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
