apiVersion: v1
kind: Service
metadata:
  # create k8 service in the namespace `django-app`
  # it exposes pod with label `app: nginx` within cluster on port 80 and 30005 on the node for external traffic.
  name: nginx-service
  namespace: django-app
  labels:
    app: nginx-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    app: nginx
