apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret-credentials
  namespace: django-app
  labels:
    app: postgres
data:
  POSTGRES_DB: "django_app"
  POSTGRES_USER: "django_user"
  POSTGRES_PASSWORD: "django_secert_password!@#"
