apiVersion: apps/v1
kind: Deployment
metadata:
  # deploy postgres in the same namespace as django-app
  name: postgres
  namespace: django-app
spec:
  # deploy single replica of postgres database with persistant storage of 1Gi capacity
  # and use the configMap to set the environment variables
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgres
        image: postgres:16.0
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: db-secret-credentials
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgres/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: postgres-pvc
