apiVersion: v1
kind: Service
metadata:
  # define a NodePort svc named postgres-service in the namespace django-app
  # It exposes postgres svc running in pods labels with `app: postgresdb` on port 5432 within cluster
  # External client can access the service on node's IP and Port 30004 from outside cluster.
  name: postgres-service
  namespace: django-app
  labels:
    app: postgres-svc
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30004
  selector:
    app: postgresdb
